{% set name = "deeplearnjs" %}
{% set version = "0.12.5" %}
{% set sha256 = "7c47f6051ae2780a3e0575468e5d1c8a28cfaeaf3028b96f32c8ba02841ed907" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/PAIR-code/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  script: npm install -g .

requirements:
  build:
    - nodejs
  
test:
  commands:
    - npm list -g deeplearn
  requires:
    - nodejs
   
about:
  home: https://github.com/PAIR-code/deeplearnjs
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Hardware-accelerated deep learning and linear algebra (NumPy) library for the web.'
  description: |
    deeplearn.js is an open source hardware-accelerated JavaScript library for machine 
    intelligence. deeplearn.js brings performant machine learning building blocks to the 
    web, allowing you to train neural networks in a browser or run pre-trained models in 
    inference mode. 
  doc_url: https://deeplearnjs.org/docs/tutorials/
  dev_url: https://github.com/PAIR-code/deeplearnjs

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
