travis:
  secure:
    BINSTAR_TOKEN: NbrRXzmq2IyIAFwfLx60B3nRgvCYw7TBkGPuTudjtnLG6cMOUtK2F7S82xVJkdjRg+0h/BqhECLDJtNif1I1Rgyf9TrShwCLCMF8O8dc3eetOvjD91BXPlZfcRd6B2A++jzKHJGDbh5FbaabVKGTFvVRlzr3YZd2pKl1yKYgulAZdinFoEb7aes0e3iuOEA6lTdwmAyhuk6sbBk1/69NZx+HfVt5PPa9b+x0kNVYWCMVhuMnDa2vGM/dDpD6JIwDDgkfGFux4m6Ybp7/5eIGVD67dtDKKLz4uBhQhErdxPKzjdw4g+83qR4Hvzc0A6lEHzLYtJ/IqxVVsWZ5KAyCb8JAb3k9AP1eleXVwE8CncG0J7ySuLPd6316kP/bXBBL+X9msuWJu7DJYp4hmzhaqCfcUK+yR1A67nsm3UmLkNK6AJ0YLu3Dj/vNBl3cP5jZOE0GqiF7xJpXuKp3C2R51ROXjlgYOa/eJaxoGEWhaLz8QDOCnoYnSNNG9uQfE89HoLISLXPShJGk+/p5QXjpDCW3ED57UdavAiUTIrtD+YyncGHhsbQ9rlwrHuri4xNESMP/1ZtHtCclpqMjLCxR9/Fdh2mOfODqEPLgitY2tfVdsQdhGl8cQXLtfhLhGCNOLWSho9h/dWyAFNr+T8Y620gtPJpzrh0DB7F65CKygA4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
