travis:
  secure:
    BINSTAR_TOKEN: qLOw+Rl1F1FV4FkDqyxN+BV4GhF5Umo99yUoxt4NNCqgzGBtKIub/PPX+jxrBFZzFyIe6GB8QOviTHHlJAoh1Iq16Oq8oVsMdYdP59sjvAtbznlkgghrWOnT8HAeA8dJV52KWpeBl8jUTMg7PR8FA6W/T1mkRVxpDwbv02eI98V7QmFf6RN7h14Qw2knt38j2HItgsvyrQe2hblUuuPr/6wD5DEtWur5ckhCAsTZWFNoS1c5JZGYOWV9/8IojYOpB35WqsKQFT2N8wI/oez7DKg4nth+dLDCjFDJGd/HPdMLR0AuqVSNMSFR8EXO68/uiYsiqUvXaTxo/CU8G7OtV/S1QWReykwSD6qQALrDRZeZamhWckhtFOKdwrGO6KV5NymtvKNY3PfNTdW4//e7GCETESZXnDQmsI8hEf6f3lPYuwC0F8jgPs6Pe+pLnRHs0XGZv4Mil1tUIvnfrI8WjgCpJWCz9w3GLlLwpDu0RjBjuEoDcIkg5efIVUn6Y8E3zmQTReO6XkH5+G4Dw9D+78pU0y6uuHhWIYaW/+ZCVXBo13I6HWmccYK0zKMLIWqTbjV59TJrkmw/m7xvKy4Ks7UrP1lu2weqCxZ11hIsnULjawGtMag5Usueam99dRlgKHS/KVp63qQqYmlM1y4hvJa6C14Dh7IzkY5HlPV3RAA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
