travis:
  secure:
    BINSTAR_TOKEN: 1JvVPkwQG3qo6GvST8WjRTvKWP9LS8/GSa3NTVQDx5zSeu/QfaDcKcYp0q4v1j1DGpxM7oV6YjGoY634FKIsW4PtUlgEV0pCG7iLzfy6BoZpwf3WSUQvfw1xAoaDZu2RKD9BOF4AV6RbZeTFQ3RNLhwQILsrqt6csQA2aALmRcrpa3N2Y4qEo7EYHeZxD/8fPnladsUyCOlt5D1LVmkF4fR8MFas+JIkcTA/x9/mjrLtCv847vqZ2J8PRnOi5e81/JbOa9aPdpYpUUGaVcr9MKr+NRJJF8Ozw1r5NSuJ98LI6zO7NXn8xxotzzqEZD5NrJvaOgUUB2kc1lCAV8ztTzWH2iJMummFMZOcFFaAqsSaVOij85MClOaZJqvZHfeCht120df4Fps99x90fukjFMZ7bQxkekNLW23wZbvUcFwMcUQ1ApdmsLALi4DaOAvJ7w5kmyvd08+iYyJBejverFkHZls4xmjECFHj3lnKb1iPnHQMeeORP/EM8w31pPy40zHBJBCkNqDHhKXq/6zjf5T4CABZ5LzGdm/kXY2HiGML3iUu7SkOoPiwd6ccwJ+7g57gXoRSzfR9TlZm1nQnp+oNiT4TT37z+OugMc5zZwd0eUQ6FKGVUhV39BgYbQHByACY6TvDQL2krYiWRqyBOHejPlq4nxGMj0vDm7aOgNE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
