travis:
  secure:
    BINSTAR_TOKEN: YNVUtN1shuNMGT2u3KcteOvKK6apmGoFt2vD2mMBHUcgE0zQISFaCHF6R/NZGmSSdqYskxsRw7WFEU6kmP17+7St6cJ8Rp9QQVf9uSegIER8mtMsJYK/Tvoa3/DJqiDj/upZjm0K1u2TJCAfy3hSRgF8u/FcBeIXncf9lOn2pabl0oad3FfG947DtzXlMXmiBIIDfmbn1K6fFRvj63crrwUkhJ3CQWEQTdfMuJ/IXTnKTpBwkBNIXZKBEK0SY0e9VQ1FOH5evAMesZ0B6F3Ap0zravltJKkHmOHfxi5dJ876/9C9etYkyhU8/Gopm2XzeBvPcNZ4oo93yDc3ENpTLywOKJ3mW0q0TpNEOnuXsFu7HaYqwS0ISqa8WWB+tJGkq8A16g86bA9lBz56KyPcueG0TLA8tK64/HK+VYpZ8svPzyQ58HswTPNIlVs83A9tbV1c+KKBMvZngd1QXeqXfIcCsMJEmucv8sxv8KpZ+2CcWNna0CkKija3Fcsho2xRu2YruxPQsdn2d+kVNd8xklUFoyYa9wWDTqz7s3m35w3f3TjRXEouuIgPGst20TZiZKNLnoeBcamDPtZp+klE6e+go3HnWl2UxLtoEQ1mbPOnm4LY+o3u5aI+Jodc9sVx540MadcC7AT3+5dAKhmsxdlrHzLI1Levqbjci8+XhPk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
